### PR TITLE
long rod cases fixed

### PR DESCRIPTION
**Pull request by hapfang**
After extensive testing, it has been confirmed that ENRICO is able to produce consistent results for the long rod test case with both Nek5000 and nekRS solvers. The related case files have been added to the repository together with a zipped checkpoint file containing the velocity solutions.

### CODE REVIEW

**Comment by paulromano** [comment]
Thanks @hapfang. I'm out on vacation this week but will take a look early next week.

**Review by paulromano — COMMENTED** [review]
It looks like we have a rod_l.rea file in both `singlerod/long/openmc_nek5000` and `singlerod/long/`. The latter version still references rod_l.run01. Should we remove that file and have the new version in `singlerod/long` with symbolic links in both the `openmc_nek5000` and `openmc_nekrs` directories?

**Comment by RonRahaman** [comment]
I propose these subdirectories for `tests/singlerod/long`.  They're similar to the dirs for the shortrod case.  The --> indicates a symlink.  Note that there are no files directly in the top-level `tests/singlerod/long` dir; all the files are in its the subdirectories.  What do you think?

- openmc/
  * geometry.xml
  * materials.xml
  * settings.xml
- nek5000/
  * rod_l.map (currently in tests/singlerod/long/)
  * rod_l.rea (currently in tests/singlerod/long/openmc_nek5000)
  * rod_l.usr  (currently in tests/singerod/long/openmc_nek5000)
  * SIZE
- nekrs/
  * rod_l.co2
  * rod_l.oudf
  * rod_l.par
  * rod_l.re2
  * rod_l.run03.tgz
  * rod_l.udf
  * rod_l.usr
- openmc_heat_surrogate/
  * enrico.xml
  * geometry.xml --> ../openmc/geometry.xml
  * materials.xml --> ../openmc/materials.xml
  * settings.xml --> ../openmc/settings.xml
- openmc_nek5000/
  * enrico.xml
  * geometry.xml --> ../openmc/geometry.xml
  * materials.xml --> ../openmc/materials.xml
  * settings.xml --> ../openmc/settings.xml
  * rod_l.map --> ../nek5000/rod_l.map
  * rod_l.rea --> ../nek5000/rod_l.rea
  * rod_l.run03.tgz --> ../nekrs/rod_l.run03.tgz
  * rod_l.usr --> ../nek5000/rod_l.usr
  * SIZE --> ../nek5000/SIZE
- openmc_nekrs/
  * enrico.xml
  * geometry.xml --> ../openmc/geometry.xml
  * materials.xml --> ../openmc/materials.xml
  * settings.xml --> ../openmc/settings.xml
  * rod_l.co2 --> ../nekrs/rod_l.co2
  * rod_l.oudf --> ../nekrs/rod_l.oudf
  * rod_l.par --> ../nekrs/rod_l.par
  * rod_l.re2 --> ../nekrs/rod_l.re2
  * rod_l.run03.tgz --> ../nekrs/rod_l.run03.tgz
  * rod_l.udf --> ../nekrs/rod_l.udf
  * rod_l.usr --> ../nekrs/rod_l.usr

**Comment by paulromano** [comment]
@RonRahaman That sounds like a good structure to me.

**Comment by hapfang** [comment]
Thanks Ron. The directory structures make sense to me. I will re-arrange the folders accordingly.

**Comment by RonRahaman** [comment]
Thanks Jun!  Make sure you use `git mv` instead of normal `mv`, especially for the tarball.

**Comment by hapfang** [comment]
Great idea. Thanks for reminding.

**Comment by hapfang** [comment]
I have updated the longrod test and rearranged the subdirectories. 


```
$ ls -rlt *
openmc:
total 1968
-rw-r--r-- 1 fangj users   27002 Apr  1 22:27 geometry.xml
-rw-r--r-- 1 fangj users 1978639 Apr  1 22:27 materials.xml
-rw-r--r-- 1 fangj users     538 Apr  1 22:27 settings.xml

nek5000:
total 41656
-rw-r--r-- 1 fangj users     4601 Apr  1 22:27 SIZE
-rw-r--r-- 1 fangj users  3313685 Apr  1 22:27 rod_l.map
-rw-r--r-- 1 fangj users 39319913 Apr  1 23:02 rod_l.rea
-rw-r--r-- 1 fangj users     4625 Apr  1 23:06 rod_l.usr

nekrs:
total 33196
-rw-r--r-- 1 fangj users  1094536 Apr  1 22:52 rod_l.co2
-rw-r--r-- 1 fangj users      973 Apr  1 22:52 rod_l.oudf
-rw-r--r-- 1 fangj users 12454508 Apr  1 22:52 rod_l.re2
-rw-r--r-- 1 fangj users 20415117 Apr  1 22:56 rod_l.run03.tgz
-rw-r--r-- 1 fangj users     2458 Apr  6 12:11 rod_l.udf
-rw-r--r-- 1 fangj users     6833 Apr  6 12:11 rod_l.usr
-rw-r--r-- 1 fangj users      389 Apr  6 12:13 rod_l.par

openmc_heat_surrogate:
total 4
-rw-r--r-- 1 fangj users 2022 Apr  1 22:29 enrico.xml
lrwxrwxrwx 1 fangj users   22 Apr  6 12:15 geometry.xml -> ../openmc/geometry.xml
lrwxrwxrwx 1 fangj users   23 Apr  6 12:15 materials.xml -> ../openmc/materials.xml
lrwxrwxrwx 1 fangj users   22 Apr  6 12:16 settings.xml -> ../openmc/settings.xml

openmc_nek5000:
total 4
-rw-r--r-- 1 fangj users 476 Apr  1 23:00 enrico.xml
lrwxrwxrwx 1 fangj users  22 Apr  6 12:17 geometry.xml -> ../openmc/geometry.xml
lrwxrwxrwx 1 fangj users  23 Apr  6 12:17 materials.xml -> ../openmc/materials.xml
lrwxrwxrwx 1 fangj users  22 Apr  6 12:17 settings.xml -> ../openmc/settings.xml
lrwxrwxrwx 1 fangj users  20 Apr  6 12:18 rod_l.map -> ../nek5000/rod_l.map
lrwxrwxrwx 1 fangj users  24 Apr  6 12:18 rod_l.run03.tgz -> ../nekrs/rod_l.run03.tgz
lrwxrwxrwx 1 fangj users  15 Apr  6 12:19 SIZE -> ../nek5000/SIZE
lrwxrwxrwx 1 fangj users  20 Apr  6 12:19 rod_l.usr -> ../nek5000/rod_l.usr
lrwxrwxrwx 1 fangj users  20 Apr  6 12:19 rod_l.rea -> ../nek5000/rod_l.rea

openmc_nekrs:
total 20
-rw-r--r-- 1 fangj users  474 Apr  1 22:52 enrico.xml
-rw-r--r-- 1 fangj users  389 Apr  1 22:52 rod_l.par
-rw-r--r-- 1 fangj users 2258 Apr  1 22:58 rod_l.udf
-rw-r--r-- 1 fangj users 6364 Apr  1 22:58 rod_l.usr
lrwxrwxrwx 1 fangj users   22 Apr  6 12:21 geometry.xml -> ../openmc/geometry.xml
lrwxrwxrwx 1 fangj users   23 Apr  6 12:21 materials.xml -> ../openmc/materials.xml
lrwxrwxrwx 1 fangj users   22 Apr  6 12:21 settings.xml -> ../openmc/settings.xml
lrwxrwxrwx 1 fangj users   18 Apr  6 12:21 rod_l.co2 -> ../nekrs/rod_l.co2
lrwxrwxrwx 1 fangj users   18 Apr  6 12:21 rod_l.re2 -> ../nekrs/rod_l.re2
lrwxrwxrwx 1 fangj users   24 Apr  6 12:21 rod_l.run03.tgz -> ../nekrs/rod_l.run03.tgz
lrwxrwxrwx 1 fangj users   19 Apr  6 12:22 rod_l.oudf -> ../nekrs/rod_l.oudf
```

**Review by paulromano — APPROVED** [review]
Looks good to me now! @RonRahaman do you want to take a look before we merge?

**Review by RonRahaman — APPROVED** [review]

**Comment by RonRahaman** [comment]
Done!  @hapfang and @emerzari thanks for all the hard work it took to straighten this out!

**Pull request merged**
