### PR TITLE
Update OpenMC submodule

### PR DESCRIPTION
**Pull request by paulromano**
Pretty straightforward submodule update here for OpenMC. Two lines needed to be fixed due to introducing some enums in OpenMC.

### CODE REVIEW

**Comment by pshriwise** [comment]
Ended up making a nearly identical set of changes yesterday myself. Thanks for submitting them instead of letting them sit in a local branch like I did :) 

Will merge at the end of the day assuming CI is happy.

**Comment by paulromano** [comment]
Pretty sure I know why the OpenMC test is failing but it's going to require a fix in OpenMC...

**Comment by paulromano** [comment]
My suspicion was correct -- after a fix in OpenMC was merged and I updated the submodule, tests are passing here.

**Comment by pshriwise** [comment]
Good to see! Also nice to know we're hitting that case somewhere in the automated testing ecosystem. :)

**Pull request merged**
