### PR TITLE
Output heat source with NekRSDriver

### PR DESCRIPTION
**Pull request by RonRahaman**
This PR allows the heat source from OpenMC to be output to a nek .fld file.
* This capability is only implemented for nekRS coupling
* It works by passing the `localq` vector to `writeFld` as a passive scalar.  To do so, `localq` is wrapped as an `occa::memory` object using `occa::cpu::wrapMemorry`.  This does not require copying the contents of `localq`.  
* The heat source is output to a new field file prefixed with `qsc`, where the heat source is the only passive scalar.  
* The units are W/cm^3
* This capability enabled by default, but it can disabled off by specifying `<output_heat_source>false</output_heat_source>` in the `<heat_fluids>` block of `enrico.xml`.

### CODE REVIEW

**Comment by RonRahaman** [comment]
I don't think I want to merge this as-is.  I want to take the long-term solution of storing localq as an unsolved passive scalar, and then do that for both nekRS and Nek5000

**Comment by paulromano** [comment]
@RonRahaman sounds good, let me know when you have a long-term solution ready

**Comment by RonRahaman** [comment]
I'd like to merge this as is, and I've removed "WIP" from the subject.  My ideal solution was to store localq as an unsolved passive scalar, but that will not work for several reasons.  I've also set the "output_heat_source" in enrico.xml to be false; this makes the option consistent with PR #142

**Review by paulromano — CHANGES_REQUESTED** [review]
Code changes looks good to me. Only thing needed is to add the new user input option in `docs/source/input.rst`?

So what's the plan with #142 if we're merging this?

**Comment by hapfang** [comment]
The PR of #142 looks good to me. I am gonna approve it.

**Comment by paulromano** [comment]
@hapfang I'm confused as to why you just merged #142. @RonRahaman said that the approach in that PR will not work. Am I missing something here?

**Comment by hapfang** [comment]
@paulromano Thanks for pointing it out. Ron and I have some additional communication via emails.  My understanding is that unlike in nekRS, the localq can still be stored as an unsolved passive scalar in Nek5000. Together with the newly added option `<output_heat_source>`, the PR in #142 seems to be complete to me. Well, I could be wrong. @RonRahaman, it will be appreciated if you could confirm it.

**Comment by RonRahaman** [comment]
Sorry the context became a little unclear.  #142 uses the passive scalar approach for Nek5000 only.  Unfortunately, we can't use the passive scalar approach with nekRS, so this PR (#141) implements a viable solution for NekRS only.  

This issue is that, in a conjugate heat transfer simulation in nekRS, additional passive scalars are defined on the velocity mesh (not the temperature mesh).  Hence, we can't use a passive scalar for our heat source.  

I changed the title of this PR, hopefully to make it clearer, and I will resolve the conflict.

**Pull request closed without merging**
